// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/categories": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Categories"
                ],
                "summary": "Create category",
                "parameters": [
                    {
                        "description": "Create category request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Category"
                        }
                    }
                }
            }
        },
        "/admin/categories/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Categories"
                ],
                "summary": "Update category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update category request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Category"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin - Categories"
                ],
                "summary": "Delete category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/feedback/pending": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Moderation"
                ],
                "summary": "Get pending feedback",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/feedback/{id}/approve": {
            "post": {
                "tags": [
                    "Admin - Moderation"
                ],
                "summary": "Approve feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            }
        },
        "/admin/feedback/{id}/reject": {
            "post": {
                "tags": [
                    "Admin - Moderation"
                ],
                "summary": "Reject feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            }
        },
        "/admin/feedback/{id}/response": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Moderation"
                ],
                "summary": "Add official response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Official response",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            }
        },
        "/admin/feedback/{id}/status": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Moderation"
                ],
                "summary": "Update feedback status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            }
        },
        "/admin/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Settings"
                ],
                "summary": "Get all settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Setting"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Settings"
                ],
                "summary": "Update setting",
                "parameters": [
                    {
                        "description": "Update setting request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.UpdateSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/settings/initialize": {
            "post": {
                "tags": [
                    "Admin - Settings"
                ],
                "summary": "Initialize default settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin - Stats"
                ],
                "summary": "Get dashboard statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackStats"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "List categories",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Only active categories",
                        "name": "active_only",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Category"
                            }
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Category"
                        }
                    }
                }
            }
        },
        "/comments/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Get comment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.Comment"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Update comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update comment request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.UpdateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.Comment"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Comments"
                ],
                "summary": "Delete comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/comments/{id}/reactions": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Add reaction to comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reaction request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Comments"
                ],
                "summary": "Remove reaction from comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/comments/{id}/replies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Get replies to a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.RepliesResponse"
                        }
                    }
                }
            }
        },
        "/feedback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "List feedback",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search text",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by (new, top, trending, most_commented)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Create feedback",
                "parameters": [
                    {
                        "description": "Create feedback request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.CreateFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            }
        },
        "/feedback/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Get feedback statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackStats"
                        }
                    }
                }
            }
        },
        "/feedback/trending": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Get trending feedback",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackResponse"
                            }
                        }
                    }
                }
            }
        },
        "/feedback/{feedback_id}/comments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "List comments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "feedback_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent comment ID",
                        "name": "parent_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort by (created_at, like_count)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc, desc)",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.ListCommentsResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Create comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "feedback_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create comment request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/comment.Comment"
                        }
                    }
                }
            }
        },
        "/feedback/{feedback_id}/comments/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Get comment statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "feedback_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.CommentStats"
                        }
                    }
                }
            }
        },
        "/feedback/{feedback_id}/subscription": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Check subscription status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "feedback_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/feedback/{feedback_id}/unsubscribe": {
            "delete": {
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Unsubscribe from feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "feedback_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/feedback/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Get feedback by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Update feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update feedback request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.UpdateFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Feedback"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Feedback"
                ],
                "summary": "Delete feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/feedback/{id}/vote": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback"
                ],
                "summary": "Vote on feedback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vote request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.VoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Get public settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "List user subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscriptionResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Subscribe to feedback/category",
                "parameters": [
                    {
                        "description": "Subscribe request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Subscription"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Update subscription preferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update subscription request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Subscription"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Unsubscribe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "comment.Attachment": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "uploadedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "comment.Comment": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comment.Attachment"
                    }
                },
                "authorAvatar": {
                    "type": "string"
                },
                "authorEmail": {
                    "type": "string"
                },
                "authorId": {
                    "description": "Author info",
                    "type": "string"
                },
                "authorName": {
                    "type": "string"
                },
                "content": {
                    "description": "Content",
                    "type": "string"
                },
                "contentHtml": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "depth": {
                    "description": "Depth for nested replies",
                    "type": "integer"
                },
                "dislikeCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isAnonymous": {
                    "type": "boolean"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "isEdited": {
                    "type": "boolean"
                },
                "isPinned": {
                    "description": "Features",
                    "type": "boolean"
                },
                "likeCount": {
                    "type": "integer"
                },
                "metadata": {
                    "description": "Metadata",
                    "type": "object",
                    "additionalProperties": {}
                },
                "moderatedAt": {
                    "type": "string"
                },
                "moderatedBy": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "pinnedAt": {
                    "type": "string"
                },
                "reactionCounts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "rejectionReason": {
                    "type": "string"
                },
                "replyCount": {
                    "description": "Stats",
                    "type": "integer"
                },
                "reportCount": {
                    "type": "integer"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "rootId": {
                    "type": "string"
                },
                "status": {
                    "description": "Moderation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/comment.CommentStatus"
                        }
                    ]
                },
                "tenantId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "comment.CommentStats": {
            "type": "object",
            "properties": {
                "approvedCount": {
                    "type": "integer"
                },
                "pendingCount": {
                    "type": "integer"
                },
                "reactionBreakdown": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "rejectedCount": {
                    "type": "integer"
                },
                "totalComments": {
                    "type": "integer"
                }
            }
        },
        "comment.CommentStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected",
                "spam"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusApproved",
                "StatusRejected",
                "StatusSpam"
            ]
        },
        "comment.ListCommentsResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comment.Comment"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "comment.RepliesResponse": {
            "type": "object",
            "properties": {
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comment.Comment"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.AddAttachmentRequest": {
            "type": "object",
            "required": [
                "name",
                "storageId",
                "url"
            ],
            "properties": {
                "mimeType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "storageId": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.Attachment": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "storageId": {
                    "description": "ID from storage service",
                    "type": "string"
                },
                "uploadedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.Category": {
            "type": "object",
            "properties": {
                "children": {
                    "description": "For response - nested children (not stored in DB)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Category"
                    }
                },
                "color": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "feedbackCount": {
                    "description": "Stats",
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "description": "Parent category for hierarchical structure",
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "tenantId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.CategorySummary": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.ContributorStats": {
            "type": "object",
            "properties": {
                "commentCount": {
                    "type": "integer"
                },
                "feedbackCount": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "voteCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "parentId": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.CreateCommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000
                },
                "isAnonymous": {
                    "type": "boolean"
                },
                "parentId": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.CreateFeedbackRequest": {
            "type": "object",
            "required": [
                "description",
                "title"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.AddAttachmentRequest"
                    }
                },
                "categoryId": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 10000
                },
                "isAnonymous": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tenantId": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "github_com_minisource_feedback_internal_models.Feedback": {
            "type": "object",
            "properties": {
                "approvedAt": {
                    "type": "string"
                },
                "attachments": {
                    "description": "Attachments (uploaded via storage service)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Attachment"
                    }
                },
                "authorAvatar": {
                    "type": "string"
                },
                "authorEmail": {
                    "type": "string"
                },
                "authorId": {
                    "description": "Author information",
                    "type": "string"
                },
                "authorName": {
                    "type": "string"
                },
                "categoryId": {
                    "description": "Category and tags",
                    "type": "string"
                },
                "categoryName": {
                    "type": "string"
                },
                "commentCount": {
                    "type": "integer"
                },
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Soft delete",
                    "type": "string"
                },
                "deletedBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "downvotes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isAnonymous": {
                    "type": "boolean"
                },
                "officialResponse": {
                    "description": "Admin response",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.OfficialResponse"
                        }
                    ]
                },
                "status": {
                    "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackStatus"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tenantId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "trendingScore": {
                    "description": "Trending score (calculated based on votes, comments, views, and time decay)",
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                },
                "upvotes": {
                    "description": "Voting",
                    "type": "integer"
                },
                "viewCount": {
                    "description": "Engagement metrics",
                    "type": "integer"
                },
                "voteScore": {
                    "description": "upvotes - downvotes",
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.FeedbackResponse": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.Attachment"
                    }
                },
                "authorId": {
                    "type": "string"
                },
                "authorName": {
                    "type": "string"
                },
                "category": {
                    "$ref": "#/definitions/github_com_minisource_feedback_internal_models.CategorySummary"
                },
                "categoryId": {
                    "type": "string"
                },
                "commentCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "downvotes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isSubscribed": {
                    "type": "boolean"
                },
                "officialResponse": {
                    "$ref": "#/definitions/github_com_minisource_feedback_internal_models.OfficialResponse"
                },
                "status": {
                    "$ref": "#/definitions/github_com_minisource_feedback_internal_models.FeedbackStatus"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "upvotes": {
                    "type": "integer"
                },
                "userVote": {
                    "type": "string"
                },
                "viewCount": {
                    "type": "integer"
                },
                "voteScore": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.FeedbackStats": {
            "type": "object",
            "properties": {
                "feedbackByCategory": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "feedbackByStatus": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "recentActivity": {
                    "description": "Last 24 hours",
                    "type": "integer"
                },
                "topContributors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.ContributorStats"
                    }
                },
                "totalComments": {
                    "type": "integer"
                },
                "totalFeedback": {
                    "type": "integer"
                },
                "totalVotes": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.FeedbackStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected",
                "under_review",
                "planned",
                "in_progress",
                "completed",
                "closed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusApproved",
                "StatusRejected",
                "StatusUnderReview",
                "StatusPlanned",
                "StatusInProgress",
                "StatusCompleted",
                "StatusClosed"
            ]
        },
        "github_com_minisource_feedback_internal_models.OfficialResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "respondedAt": {
                    "type": "string"
                },
                "respondedBy": {
                    "type": "string"
                },
                "respondedByName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.Setting": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isPublic": {
                    "description": "If true, visible to non-admins",
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SettingType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "github_com_minisource_feedback_internal_models.SettingType": {
            "type": "string",
            "enum": [
                "string",
                "number",
                "boolean",
                "json"
            ],
            "x-enum-varnames": [
                "SettingTypeString",
                "SettingTypeNumber",
                "SettingTypeBool",
                "SettingTypeJSON"
            ]
        },
        "github_com_minisource_feedback_internal_models.SubscribeRequest": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "emailEnabled": {
                    "type": "boolean"
                },
                "feedbackId": {
                    "type": "string"
                },
                "pushEnabled": {
                    "type": "boolean"
                },
                "subscribeAll": {
                    "type": "boolean"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscriptionType"
                    }
                }
            }
        },
        "github_com_minisource_feedback_internal_models.Subscription": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "description": "Subscribe to category",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "emailEnabled": {
                    "description": "Notification preferences",
                    "type": "boolean"
                },
                "feedbackId": {
                    "description": "What to subscribe to",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "description": "Status",
                    "type": "boolean"
                },
                "pushEnabled": {
                    "type": "boolean"
                },
                "subscribeAll": {
                    "description": "Subscribe to all new feedback",
                    "type": "boolean"
                },
                "tenantId": {
                    "type": "string"
                },
                "types": {
                    "description": "Subscription types",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscriptionType"
                    }
                },
                "unsubscribedAt": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userEmail": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "emailEnabled": {
                    "type": "boolean"
                },
                "feedbackId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pushEnabled": {
                    "type": "boolean"
                },
                "subscribeAll": {
                    "type": "boolean"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscriptionType"
                    }
                }
            }
        },
        "github_com_minisource_feedback_internal_models.SubscriptionType": {
            "type": "string",
            "enum": [
                "new_feedback",
                "feedback_update",
                "status_change",
                "new_comment",
                "official_response",
                "all"
            ],
            "x-enum-varnames": [
                "SubNewFeedback",
                "SubFeedbackUpdate",
                "SubStatusChange",
                "SubNewComment",
                "SubOfficialResponse",
                "SubAll"
            ]
        },
        "github_com_minisource_feedback_internal_models.UpdateCategoryRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "icon": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "parentId": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                }
            }
        },
        "github_com_minisource_feedback_internal_models.UpdateCommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000
                }
            }
        },
        "github_com_minisource_feedback_internal_models.UpdateFeedbackRequest": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 10000
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "github_com_minisource_feedback_internal_models.UpdateSettingRequest": {
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "github_com_minisource_feedback_internal_models.UpdateSubscriptionRequest": {
            "type": "object",
            "properties": {
                "emailEnabled": {
                    "type": "boolean"
                },
                "pushEnabled": {
                    "type": "boolean"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_minisource_feedback_internal_models.SubscriptionType"
                    }
                }
            }
        },
        "github_com_minisource_feedback_internal_models.VoteRequest": {
            "type": "object",
            "required": [
                "voteType"
            ],
            "properties": {
                "voteType": {
                    "enum": [
                        "up",
                        "down"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_minisource_feedback_internal_models.VoteType"
                        }
                    ]
                }
            }
        },
        "github_com_minisource_feedback_internal_models.VoteType": {
            "type": "string",
            "enum": [
                "up",
                "down"
            ],
            "x-enum-varnames": [
                "VoteUp",
                "VoteDown"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5012",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Feedback Service API",
	Description:      "Feedback management service for Minisource",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
